#include "arduino_secrets.h"
/* 
  Sketch generated by the Arduino IoT Cloud Thing "Untitled 2"
  https://create.arduino.cc/cloud/things/8ff206dd-8ee1-4eba-878b-52b313bf5a84 

  Arduino IoT Cloud Variables description

  The following variables are automatically generated and updated when changes are made to the Thing

  CloudIlluminance light;
  bool led;
  bool buzzer;

  Variables which are marked as READ/WRITE in the Cloud Thing will also have functions
  which are called when their values are changed from the Dashboard.
  These functions are generated with the Thing and added at the end of this sketch.
*/

int light_pin = 5;
int buzz_pin = 7;
bool val;
#include <Arduino.h>
#include <hp_BH1750.h>  //  include the library
hp_BH1750 BH1750;
#include "thingProperties.h"

void setup() {
 Serial.begin(9600);
  // Initialize serial and wait for port to open:
   pinMode(light_pin, OUTPUT);
   pinMode(buzz_pin, OUTPUT);

  delay(1000);

  // Defined in thingProperties.h
  initProperties();

  // Connect to Arduino IoT Cloud
  ArduinoCloud.begin(ArduinoIoTPreferredConnection);

  bool avail = BH1750.begin(BH1750_TO_GROUND);
  setDebugMessageLevel(2);
  ArduinoCloud.printDebugInfo();
}

void loop() {
  ArduinoCloud.update();
  // Your code here
  
  BH1750.start();  
  light = BH1750.getLux(); 

  if (light < 200)
  {
    led = HIGH;
    onLedChange();
    val = true;
  }
  else
  {
    led = LOW;
    onBuzzerChange();
    val = false;
  }
  
}

void onLedChange() {
  digitalWrite(light_pin, HIGH);
  delay(2000);
  digitalWrite(light_pin, LOW);
  delay(500);
}


void onBuzzerChange() {
  digitalWrite(buzz_pin, HIGH);
  delay(2000);
  digitalWrite(buzz_pin, LOW);
}


